// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzTERTIe6nL0NFus9-O6S3aX6ceEk4O_s',
    appId: '1:976599680188:web:5ea4e97dafff7ea8f7fcb9',
    messagingSenderId: '976599680188',
    projectId: 'cuida-820ab',
    authDomain: 'cuida-820ab.firebaseapp.com',
    storageBucket: 'cuida-820ab.appspot.com',
    measurementId: 'G-4FHTE26P0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQCvaM6Re3hF0ezW0aZYCuc4U2QN-NIdg',
    appId: '1:976599680188:android:4b8b087bf92c6231f7fcb9',
    messagingSenderId: '976599680188',
    projectId: 'cuida-820ab',
    storageBucket: 'cuida-820ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC05aKyzXsScHm5KHznrgmjBiVqvP7U19U',
    appId: '1:976599680188:ios:a14ef71741c3cbb6f7fcb9',
    messagingSenderId: '976599680188',
    projectId: 'cuida-820ab',
    storageBucket: 'cuida-820ab.appspot.com',
    iosBundleId: 'br.com.w2esolucoes.cuida',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC05aKyzXsScHm5KHznrgmjBiVqvP7U19U',
    appId: '1:976599680188:ios:a14ef71741c3cbb6f7fcb9',
    messagingSenderId: '976599680188',
    projectId: 'cuida-820ab',
    storageBucket: 'cuida-820ab.appspot.com',
    iosBundleId: 'br.com.w2esolucoes.cuida',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzTERTIe6nL0NFus9-O6S3aX6ceEk4O_s',
    appId: '1:976599680188:web:a51d9be871615450f7fcb9',
    messagingSenderId: '976599680188',
    projectId: 'cuida-820ab',
    authDomain: 'cuida-820ab.firebaseapp.com',
    storageBucket: 'cuida-820ab.appspot.com',
    measurementId: 'G-V5D3THZ71G',
  );
}
