// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMvYU58OEJQyZWGzxt5obQ7-QQ9CUUmhw',
    appId: '1:463065207176:web:79b3d24fb8477d4dcdaa3d',
    messagingSenderId: '463065207176',
    projectId: 'cuidaagente-21571',
    authDomain: 'cuidaagente-21571.firebaseapp.com',
    storageBucket: 'cuidaagente-21571.firebasestorage.app',
    measurementId: 'G-R85Y10KDVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD511gi6UJldSx3x92B-9hKLb2Qlyp2zRA',
    appId: '1:463065207176:android:45b814353337cd41cdaa3d',
    messagingSenderId: '463065207176',
    projectId: 'cuidaagente-21571',
    storageBucket: 'cuidaagente-21571.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoNTfkf8tA8CnxPCFSVqU-rQYEbbne3bs',
    appId: '1:463065207176:ios:e37a30ceabf1ac70cdaa3d',
    messagingSenderId: '463065207176',
    projectId: 'cuidaagente-21571',
    storageBucket: 'cuidaagente-21571.firebasestorage.app',
    iosBundleId: 'com.example.cuidaagente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoNTfkf8tA8CnxPCFSVqU-rQYEbbne3bs',
    appId: '1:463065207176:ios:e37a30ceabf1ac70cdaa3d',
    messagingSenderId: '463065207176',
    projectId: 'cuidaagente-21571',
    storageBucket: 'cuidaagente-21571.firebasestorage.app',
    iosBundleId: 'com.example.cuidaagente',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMvYU58OEJQyZWGzxt5obQ7-QQ9CUUmhw',
    appId: '1:463065207176:web:af4b07effad4b5b9cdaa3d',
    messagingSenderId: '463065207176',
    projectId: 'cuidaagente-21571',
    authDomain: 'cuidaagente-21571.firebaseapp.com',
    storageBucket: 'cuidaagente-21571.firebasestorage.app',
    measurementId: 'G-TDHQQJF4KB',
  );
}
